generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolarPage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solar_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
         menu_title: { help: "If the page will be on the menu, put a short title for the link here. Is necessary." }
      list:    
        title: Pages Management
        display: [=title, created_at, updated_at]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
