generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolarNew
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solar_new
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        sort: [created_at, desc]
        title: News Management
        display: [=title, =created_at, =updated_at]

      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
