generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolarPublication
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solar_publication
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Publications Management
        display: [=title]
      filter:
        display: [people_id] 
      form:    ~
      edit:    ~
      new:     ~
