generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolarCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solar_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: People Categories Management
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
